using System.Collections.Generic;
namespace EnhancedSpectator.Features.FearMode;
// User overrides: mask suffixes, shotgun, spray can and tongue (2026-09-21).
// Names aligned with LC-Chinese-Project c33830a95bf89d6054910979bfd524fa1197b3ad (MIT).
internal static class OriginalItemDisplayNames
{
    private static readonly Dictionary<string, string> Chinese = new Dictionary<string, string>
    {
        ["BeltBag"] = "腰包",
        ["Binoculars"] = "望远镜",
        ["Boombox"] = "手提音响",
        ["Clipboard"] = "文件夹板",
        ["DiyFlashbang"] = "自制闪光弹",
        ["ExtensionLadder"] = "伸缩梯",
        ["Flashlight"] = "手电筒",
        ["GunAmmo"] = "弹药",
        ["Jetpack"] = "喷气背包",
        ["Key"] = "钥匙",
        ["LockPicker"] = "开锁器道具",
        ["LungApparatus"] = "核心装置",
        ["MapDevice"] = "测绘装置",
        ["ProFlashlight"] = "专业手电",
        ["RadarBooster"] = "雷达增强器设备",
        ["7Ball"] = "七号魔法球",
        ["Airhorn"] = "气喇叭",
        ["BabyKiwiEgg"] = "蛋",
        ["Bell"] = "铃铛",
        ["BigBolt"] = "大螺栓",
        ["BottleBin"] = "瓶子",
        ["Brush"] = "刷子",
        ["Candy"] = "糖果",
        ["CashRegister"] = "收银机",
        ["ChemicalJug"] = "化学液罐",
        ["Clock"] = "时钟",
        ["ClownHorn"] = "小丑喇叭",
        ["Cog1"] = "大型车轴",
        ["ComedyMask"] = "喜剧面具",
        ["ControlPad"] = "控制面板",
        ["Dentures"] = "牙齿样本",
        ["DustPan"] = "簸箕",
        ["EasterEgg"] = "彩蛋",
        ["EggBeater"] = "打蛋器",
        ["EnginePart1"] = "V 型发动机",
        ["FancyCup"] = "金杯",
        ["FancyLamp"] = "华丽台灯",
        ["FancyPainting"] = "绘画作品",
        ["FishTestProp"] = "塑料鱼摆件",
        ["FlashLaserPointer"] = "镭射指示器",
        ["Flask"] = "酒壶",
        ["GarbageLid"] = "垃圾桶盖",
        ["GiftBox"] = "礼物",
        ["GoldBar"] = "金条",
        ["Hairdryer"] = "吹风机",
        ["Knife"] = "厨房用刀",
        ["MagnifyingGlass"] = "手持放大镜",
        ["MetalSheet"] = "金属薄板",
        ["MoldPan"] = "饼干烤盘",
        ["Mug"] = "饮用杯",
        ["PerfumeBottle"] = "香氛瓶",
        ["Phone"] = "老式电话",
        ["PickleJar"] = "酸黄瓜玻璃罐",
        ["PillBottle"] = "药片瓶",
        ["PlasticCup"] = "一次性塑料杯",
        ["RedLocustHive"] = "蜂巢",
        ["Remote"] = "遥控装置",
        ["Ring"] = "金属戒指",
        ["RobotToy"] = "机器人玩具",
        ["RubberDuck"] = "橡胶鸭",
        ["SeveredBone"] = "骨头",
        ["SeveredBoneRib"] = "胸肋骨架",
        ["SeveredEar"] = "耳朵",
        ["SeveredFoot"] = "脚",
        ["SeveredHand"] = "手",
        ["SeveredHeart"] = "心脏",
        ["SeveredThigh"] = "膝部",
        ["SeveredTongue"] = "舌头",
        ["SoccerBall"] = "足球玩具",
        ["SodaCanRed"] = "红罐汽水",
        ["SteeringWheel"] = "方向盘",
        ["StopSign"] = "停车标志牌",
        ["TeaKettle"] = "茶水壶",
        ["ToiletPaperRolls"] = "厕纸卷",
        ["Toothpaste"] = "牙膏管",
        ["ToyCube"] = "玩具立方体",
        ["ToyTrain"] = "火车玩具",
        ["TragedyMask"] = "悲剧面具",
        ["WhoopieCushion"] = "恶作剧坐垫",
        ["YieldSign"] = "让行标志牌",
        ["Zeddog"] = "Zed 犬",
        ["Shotgun"] = "霰弹枪",
        ["Shovel"] = "铲子",
        ["SprayPaint"] = "喷漆罐",
        ["StickyNote"] = "便签纸",
        ["StunGrenade"] = "闪爆手雷",
        ["TZPInhalant"] = "TZP 吸入喷剂",
        ["WalkieTalkie"] = "对讲机",
        ["WeedKillerBottle"] = "除草喷剂",
        ["ZapGun"] = "电弧枪",
        ["CardboardBox"] = "纸箱",
    };
    internal static string Resolve(string key, string fallback, bool chinese) =>
        chinese && Chinese.TryGetValue(key, out var label) ? label : fallback;
}
